# Generated by Django 6.0.6 on 2026-06-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muddroom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
