# Generated by Django 6.0.6 on 2026-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muddroom', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tailscale_ip', models.GenericIPAddressField()),
                ('is_reachable', models.BooleanField(default=True)),
                ('last_checked', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
