# Generated by Django 6.0.6 on 2026-06-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muddroom', '0004_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
