# Generated by Django 6.0.6 on 2026-06-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muddroom', '0005_alter_device_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
