# Generated by Django 6.0.6 on 2026-06-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muddroom', '0006_service_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='port_reachable',
            field=models.BooleanField(default=True),
        ),
    ]
